--Verificando la existencia de la Base a crear
if db_id('yii2') IS NOT NULL
	BEGIN
		USE master
		DROP DATABASE yii2
	END	
GO
--Creando la Base de datos 
CREATE DATABASE yii2
USE yii2
GO
----------------------------------------------------------------------------------
--------------------------------T A B L A S---------------------------------------
----------------------------------------------------------------------------------
---//////////////////////////////////////////////////////////
CREATE TABLE USUARIO
(
	CI INT NOT NULL PRIMARY KEY,
	NOMBRES VARCHAR(200) NOT NULL,
	APELLIDOS VARCHAR(200) NOT NULL,
	TELEFONO INT NOT NULL,
	ESTADO INT NOT NULL
);
---//////////////////////////////////////////////////////////
CREATE TABLE TIPO
(
	ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL,
	ESTADO INT NOT NULL
);
---//////////////////////////////////////////////////////////
CREATE TABLE TIPOUSUARIO
(
	CI_USUARIO INT NOT NULL PRIMARY KEY,
	ID_TIPO VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID_TIPO,CI_USUARIO),
	FOREIGN KEY(CI_USUARIO) REFERENCES USUARIO(CI)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(ID_TIPO) REFERENCES TIPO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE	
);
---//////////////////////////////////////////////////////////
CREATE TABLE CASOUSO
(
	ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	ESTADO INT NOT NULL
);
---//////////////////////////////////////////////////////////
CREATE TABLE CUTIPO
(
	ID_TIPO INT NOT NULL,
	ID_CU INT NOT NULL,
	ESTADO INT NOT NULL,
	PRIMARY KEY(ID_TIPO,ID_CU),
	FOREIGN KEY(ID_CU) REFERENCES CASOUSO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(ID_TIPO) REFERENCES TIPO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE
	
);
---//////////////////////////////////////////////////////////
CREATE TABLE MODULO
(
	ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	ESTADO INT NOT NULL
);
---//////////////////////////////////////////////////////////
CREATE TABLE CU_MODULO
(
	ID_CU INT NOT NULL,
	ID_MODULO INT NOT NULL,
	NROORDEN INT NOT NULL,
	PRIMARY KEY(ID_CU,ID_MODULO),
	FOREIGN KEY(ID_CU) REFERENCES CASOUSO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(ID_MODULO) REFERENCES MODULO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE
);
---//////////////////////////////////////////////////////////
CREATE TABLE TIPOVIDEO
(
	ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL,
	ESTADO INT NOT NULL
);
---//////////////////////////////////////////////////////////
CREATE TABLE VIDEO
(
	ID INT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	DURACION INT NOT NULL,
	COSTO INT NOT NULL,
	ESTADO INT NOT NULL,
	ID_TIPOVIDEO INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_TIPOVIDEO) REFERENCES TIPOVIDEO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
);
---//////////////////////////////////////////////////////////
CREATE TABLE FICHAPRESTAMO
(
	NRO INT NOT NULL,
	CI_USUARIO INT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(255) NOT NULL,
	DIAS INT NOT NULL,
	FECHA DATE NOT NULL,
	PRIMARY KEY(NRO),
	FOREIGN KEY(CI_USUARIO) REFERENCES USUARIO(CI)
	ON DELETE CASCADE ON UPDATE CASCADE,
);
---//////////////////////////////////////////////////////////
CREATE TABLE DETALLE
(
	NRO_FICHA INT NOT NULL,
	ID_VIDEO INT NOT NULL,
	MONTO INT NOT NULL,
	PRIMARY KEY(NRO_FICHA,ID_VIDEO),
	FOREIGN KEY(ID_VIDEO) REFERENCES VIDEO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(NRO_FICHA) REFERENCES FICHAPRESTAMO(NRO)
	ON DELETE CASCADE ON UPDATE CASCADE	
);
---//////////////////////////////////////////////////////////
